### ISSUE TITLE
`WireRope`-decorated instance method does not support `super()`

### ISSUE THREAD

**Issue by huzecong** [youknowone/wirerope#14]
First, thanks for building this wonderful library! Your approach to a unified interface to hande different callable types is inspiring for me.

Below is a record of an issue I encountered while using `WireRope`, along with my analysis:

---

If a `WireRope`-decorated instance method (e.g. `foo`) calls the super-class method of the same name, it ends up calling itself (i.e. `super().foo is foo`).

Here's a concrete example using `methodtools.lru_cache`:

```python
from methodtools import lru_cache

class Base:
    @lru_cache(maxsize=1)
    def foo(self, a: int) -> int:
        return a

    def bar(self, b: int) -> int:
        return b

class Derived(Base):
    @lru_cache(maxsize=1)
    def foo(self, a: int) -> int:
        return super().foo(a) + 1

    def bar(self, b: int) -> int:
        return super().bar(b) + 1
```

Now, to test it:
```python
>>> d = Derived()
>>> # d.foo(1)  # this loops infinitely
>>> d.bar(1)
2
>>> super(Derived, d).bar is d.bar  # this is the expected behavior
False
>>> super(Derived, d).foo is d.foo
True
```

If my understanding of the code is correct, I believe the issue is with this part in `MethodRopeMixin`: https://github.com/youknowone/wirerope/blob/cffb262c25d9820cefc695d50581d93a61e50011/wirerope/rope.py#L41-L45

According to [Python descriptor docs](https://docs.python.org/3/howto/descriptor.html#invocation-from-super):

- `d.foo` is equivalent to `d.__get__(d, Derived)`
- `super(Derived, d).foo` is equivalent to `Base.__dict__['foo'].__get__(d, Derived)`

However, for instance methods, the `wire_name` only depends on the owner (`d`) and function name (`"foo"`), but does not depend on the class in which the descriptor is defined (`Derived` in the first case, and `Base` in the second). Doing so would probably require implementing `__set_name__` in the mixin class.

Please let me know if my analysis was correct. If so, I'd be happy to send a PR to fix this.

**Comment by youknowone** [comment]
Wow, interesting analysis. To be honest, I forgot most of details of this project, so I read the codes again whenever I fix bugs. 

Your idea looks correct. The part `wire_name` only depends on the function name looks like an obvious bug. So I totally agree to the diagnosis. But I am not sure about the correct solution of it unless trying one. I will be really appreciated if you find a way to fix it.

Welcome, you are the first one who reached to the deep side of this project for years. I am really happy to know you liked the approach. This is the best moment of this project for me.

**Comment by huzecong** [comment]
Sorry for the late reply, I've been a bit busy this week and haven't found a lot of time to work on this.

I wrote a draft implementation, along with some unit tests here: https://github.com/huzecong/wirerope/compare/master..fix-super
Now it works, but only for Python 3.6 or later, because `__set_name__` was introduced in Python 3.6.

It seems that prior to that, the suggested way of implementing something like this is to set a metaclass on the containing class of the descriptor ([related StackOverflow question](https://stackoverflow.com/questions/53241645/workaround-for-not-having-set-name-in-python-versions-before-3-6)). I guess this means that it's not possible to make `super()` work correctly under Python 2.

I can modify code to keep the old behavior for versions prior to 3.6, and use the new and correct approach after 3.6. Do you think this makes sense?

**Comment by youknowone** [comment]
Yes, I agree.

There already is a few different behaviours between Python2 and Python3 due to lack of language features. So I think that approach is good enough. At the same time, I think `WireRope` can deprecate `< 3.6` not to confuse Python3 users. Anyway Python3.5 is already not maintained anymore.
