### ISSUE TITLE
Publish wheel to pypi

### ISSUE THREAD

**Issue by freeform-andre** [youknowone/wirerope#23]
Hi,

Thank you for this project! I was wondering if you could publish a wheel for it to pypy

Thanks!

**Comment by youknowone** [comment]
Thank you. wheel is uploaded now https://pypi.org/project/wirerope/#files

**Comment by freeform-andre** [comment]
> Thank you. wheel is uploaded now https://pypi.org/project/wirerope/#files

No, thank *you*! ❤️
